# Generated by Django 5.2.14 on 2026-05-24 20:01

from django.db import migrations, models


def map_room_types_to_standard_deluxe(apps, schema_editor):
    Room = apps.get_model("rooms", "Room")
    for room in Room.objects.all():
        number = "".join(ch for ch in str(room.room_number) if ch.isdigit())
        room_num = int(number) if number else 0
        if 101 <= room_num <= 108:
            room.room_type = "deluxe"
        elif 109 <= room_num <= 112:
            room.room_type = "standard"
        elif room.room_type in {"suite", "double"}:
            room.room_type = "deluxe"
        else:
            room.room_type = "standard"

        if room.status not in {"available", "occupied", "maintenance", "cleaning"}:
            room.status = "available"
        room.save(update_fields=["room_type", "status"])


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            map_room_types_to_standard_deluxe,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('cleaning', 'Cleaning In Progress')], default='available', max_length=20),
        ),
    ]
