# Generated by Django 5.2.14 on 2026-05-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_room_type_alter_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='status_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
