# Generated by Django 5.2.14 on 2026-06-07 00:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_maintenancerequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HousekeepingItemLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_name", models.CharField(max_length=160)),
                (
                    "quantity_used",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                    ),
                ),
                ("unit", models.CharField(max_length=40)),
                ("used_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="housekeeping_item_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="item_usage_logs",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "db_table": "housekeeping_items_log",
                "ordering": ["-used_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="housekeepingitemlog",
            index=models.Index(fields=["used_at"], name="housekeepin_used_at_9896b6_idx"),
        ),
        migrations.AddIndex(
            model_name="housekeepingitemlog",
            index=models.Index(fields=["item_name"], name="housekeepin_item_na_fd0ba3_idx"),
        ),
    ]
