# Generated by Django 5.2.14 on 2026-06-07 00:00

import django.core.validators
from django.db import migrations, models


def populate_stock_fields(apps, schema_editor):
    HousekeepingItemLog = apps.get_model("rooms", "HousekeepingItemLog")
    for entry in HousekeepingItemLog.objects.all():
        initial_quantity = entry.quantity_used
        quantity_in_stock = initial_quantity - entry.quantity_used
        HousekeepingItemLog.objects.filter(pk=entry.pk).update(
            initial_quantity=initial_quantity,
            quantity_in_stock=quantity_in_stock,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_housekeeping_item_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="housekeepingitemlog",
            name="initial_quantity",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="housekeepingitemlog",
            name="low_stock_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Optional custom alert threshold for this item.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="housekeepingitemlog",
            name="quantity_in_stock",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.RunPython(populate_stock_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="housekeepingitemlog",
            name="initial_quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.001)],
            ),
        ),
        migrations.AlterField(
            model_name="housekeepingitemlog",
            name="quantity_in_stock",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
