# Generated by Django 5.2.14 on 2026-06-04 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_status_toiletryitem_and_more'),
        ('rooms', '0005_room_housekeeping_last_changed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingTaskToiletry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_requirements', to='inventory.toiletryitem')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toiletry_requirements', to='rooms.housekeepingtask')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
