from django.urls import path

from inventory.views import (
    category_delete,
    category_list,
    category_update,
    inventory_dashboard,
    item_adjust_stock,
    item_create,
    item_delete,
    item_list,
    item_update,
    pos_checkout,
    pos_terminal,
    reports_center,
    sale_detail,
    sale_email,
    sale_list,
    sale_pdf,
    subcategory_delete,
    subcategory_list,
    subcategory_update,
    supplier_delete,
    supplier_list,
    supplier_update,
    transaction_list,
    toiletries_dashboard,
    toiletries_item_list,
    toiletries_item_create,
    toiletries_item_update,
    toiletries_item_delete,
    toiletry_issue,
    toiletries_movement_log,
)

urlpatterns = [
    path("", inventory_dashboard, name="inventory-dashboard"),
    path("categories/", category_list, name="inventory-categories"),
    path("categories/<int:pk>/edit/", category_update, name="inventory-category-update"),
    path("categories/<int:pk>/delete/", category_delete, name="inventory-category-delete"),
    path("subcategories/", subcategory_list, name="inventory-subcategories"),
    path("subcategories/<int:pk>/edit/", subcategory_update, name="inventory-subcategory-update"),
    path("subcategories/<int:pk>/delete/", subcategory_delete, name="inventory-subcategory-delete"),
    path("suppliers/", supplier_list, name="inventory-suppliers"),
    path("suppliers/<int:pk>/edit/", supplier_update, name="inventory-supplier-update"),
    path("suppliers/<int:pk>/delete/", supplier_delete, name="inventory-supplier-delete"),
    path("items/", item_list, name="inventory-items"),
    path("items/new/", item_create, name="inventory-item-create"),
    path("items/<int:pk>/edit/", item_update, name="inventory-item-update"),
    path("items/<int:pk>/delete/", item_delete, name="inventory-item-delete"),
    path("items/<int:pk>/adjust/", item_adjust_stock, name="inventory-item-adjust"),
    path("toiletries/", toiletries_dashboard, name="inventory-toiletries-dashboard"),
    path("toiletries/items/", toiletries_item_list, name="inventory-toiletries-items"),
    path("toiletries/items/new/", toiletries_item_create, name="inventory-toiletries-item-create"),
    path("toiletries/items/<int:pk>/edit/", toiletries_item_update, name="inventory-toiletries-item-update"),
    path("toiletries/items/<int:pk>/delete/", toiletries_item_delete, name="inventory-toiletries-item-delete"),
    path("toiletries/issue/", toiletry_issue, name="inventory-toiletries-issue"),
    path("toiletries/movements/", toiletries_movement_log, name="inventory-toiletries-movements"),
    path("transactions/", transaction_list, name="inventory-transactions"),
    path("pos/", pos_terminal, name="inventory-pos"),
    path("pos/checkout/", pos_checkout, name="inventory-pos-checkout"),
    path("sales/", sale_list, name="inventory-sales"),
    path("sales/<int:pk>/", sale_detail, name="inventory-sale-detail"),
    path("sales/<int:pk>/pdf/", sale_pdf, name="inventory-sale-pdf"),
    path("sales/<int:pk>/email/", sale_email, name="inventory-sale-email"),
    path("reports/", reports_center, name="inventory-reports"),
]
