# Generated by Django 5.2.14 on 2026-05-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=120)),
                ('ghana_card_number', models.CharField(max_length=100, unique=True)),
                ('contact_number', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gps_address', models.CharField(blank=True, max_length=255)),
                ('next_of_kin', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=40)),
                ('position', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('other', 'Other')], max_length=20)),
                ('ethnic_origin', models.CharField(blank=True, max_length=120)),
                ('religion', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
