# Generated by Django 5.2.14 on 2026-05-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='operating_hours',
        ),
        migrations.AddField(
            model_name='rota',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rota',
            name='period',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
