# Generated by Django 5.2.14 on 2026-05-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_rota_operating_hours_rota_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='passport_photo',
            field=models.ImageField(blank=True, help_text='Upload a passport-style photo.', null=True, upload_to='employee_photos/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('hotel_manager', 'Hotel Manager'), ('cleaner', 'Cleaner'), ('security', 'Security'), ('receptionist', 'Receptionist')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='religion',
            field=models.CharField(blank=True, choices=[('christian', 'Christian'), ('muslim', 'Muslim')], max_length=20),
        ),
    ]
