# Generated by Django 5.2.14 on 2026-05-31 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employee_employment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_access', models.BooleanField(default=True)),
                ('reservations_access', models.BooleanField(default=True)),
                ('rooms_access', models.BooleanField(default=True)),
                ('guests_access', models.BooleanField(default=True)),
                ('payments_access', models.BooleanField(default=True)),
                ('services_access', models.BooleanField(default=True)),
                ('housekeeping_access', models.BooleanField(default=True)),
                ('notifications_access', models.BooleanField(default=True)),
                ('analytics_access', models.BooleanField(default=True)),
                ('reports_access', models.BooleanField(default=False)),
                ('settings_access', models.BooleanField(default=False)),
                ('staff_management_access', models.BooleanField(default=False)),
                ('handovers_access', models.BooleanField(default=True)),
                ('users_roles_access', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Access Profile',
                'verbose_name_plural': 'User Access Profiles',
            },
        ),
    ]
