# Generated by Django 5.2.14 on 2026-06-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_useraccessprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccessprofile',
            name='inventory_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccessprofile',
            name='pos_access',
            field=models.BooleanField(default=True),
        ),
    ]
