# Generated by Django 5.2.14 on 2026-06-02 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_useraccessprofile_inventory_access_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=40)),
                ('employee_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='staff_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('permission_change', 'Permission Change'), ('export', 'Export'), ('print', 'Print'), ('manage', 'Manage'), ('other', 'Other')], max_length=40)),
                ('module', models.CharField(blank=True, max_length=40)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('object_id', models.CharField(blank=True, max_length=120)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='accounts_au_action_c683b9_idx'), models.Index(fields=['module', 'created_at'], name='accounts_au_module_0c9200_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('reservations', 'Reservations'), ('rooms', 'Rooms'), ('guests', 'Guests'), ('payments', 'Payments'), ('services', 'Services'), ('housekeeping', 'Housekeeping'), ('inventory', 'Inventory'), ('pos', 'Point of Sale'), ('notifications', 'Notifications'), ('analytics', 'Analytics'), ('reports', 'Reports'), ('settings', 'Settings'), ('staff_management', 'Staff Management'), ('handovers', 'Shift Handovers'), ('users_roles', 'Users & Roles')], max_length=40)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('can_print', models.BooleanField(default=False)),
                ('can_manage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='auth.group')),
            ],
            options={
                'ordering': ['role__name', 'module'],
                'constraints': [models.UniqueConstraint(fields=('role', 'module'), name='unique_role_permission_per_module')],
            },
        ),
    ]
