# Generated by Django 5.2.14 on 2026-06-07 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_notification_statushistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaverequest",
            name="approving_manager",
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="approving_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leave_requests",
                to="accounts.employee",
            ),
        ),
    ]
