# Generated by Django 5.2.14 on 2026-06-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_leave_request_employee_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('annual_leave', 'Annual Leave'), ('sick_leave', 'Sick Leave'), ('family_emergency', 'Emergency Leave'), ('maternity_leave', 'Maternity Leave'), ('paternity_leave', 'Paternity Leave'), ('unpaid_leave', 'Unpaid Leave'), ('compassionate_leave', 'Compassionate Leave'), ('study_leave', 'Study Leave'), ('other_leave', 'Other Leave'), ('suspension', 'Suspension'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('family_emergency', 'Emergency Leave'), ('study', 'Study Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('unpaid', 'Unpaid Leave'), ('compassionate', 'Compassionate Leave'), ('other', 'Other')], max_length=30),
        ),
    ]
