# Generated by Django 5.2.14 on 2026-06-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_employee_employment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
