# Generated by Django 5.2.14 on 2026-06-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerwithdrawal',
            name='collection_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money')], default='cash', max_length=20),
        ),
    ]
