# Generated by Django 5.2.14 on 2026-06-24 09:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_ownerwithdrawal_collection_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_targets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DepositCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_collected', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collection_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money')], default='cash', max_length=20)),
                ('collected_by', models.CharField(max_length=160)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_collections_recorded', to=settings.AUTH_USER_MODEL)),
                ('deposit_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='accounts.deposittarget')),
            ],
            options={
                'ordering': ['-date_collected', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='deposittarget',
            index=models.Index(fields=['week_start', 'week_end'], name='accounts_de_week_st_c5f3d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='deposittarget',
            constraint=models.UniqueConstraint(fields=('week_start', 'week_end'), name='unique_deposit_target_week_range'),
        ),
        migrations.AddIndex(
            model_name='depositcollection',
            index=models.Index(fields=['date_collected'], name='accounts_de_date_co_8f70b6_idx'),
        ),
        migrations.AddIndex(
            model_name='depositcollection',
            index=models.Index(fields=['deposit_target', 'date_collected'], name='accounts_de_deposit_5e9bcd_idx'),
        ),
    ]
