# Generated by Django 5.2.14 on 2026-06-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_deposittarget_depositcollection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposittarget',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='DepositCollection',
        ),
        migrations.DeleteModel(
            name='DepositTarget',
        ),
    ]
