# Generated by Django 5.2.14 on 2026-06-24 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_deposittarget_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownerwithdrawal',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Owner Collection', 'verbose_name_plural': 'Owner Collections'},
        ),
        migrations.RenameIndex(
            model_name='ownerwithdrawal',
            new_name='owner_colle_created_f1b388_idx',
            old_name='accounts_ow_created_dc46b5_idx',
        ),
        migrations.AddField(
            model_name='ownerwithdrawal',
            name='entry_type',
            field=models.CharField(choices=[('visit', 'Owner Visit'), ('leftover', 'Leftover')], default='visit', max_length=20),
        ),
        migrations.AlterField(
            model_name='ownerwithdrawal',
            name='collected_by',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='ownerwithdrawal',
            name='collection_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('both', 'Cash & Mobile Money')], default='cash', max_length=20),
        ),
        migrations.AddIndex(
            model_name='ownerwithdrawal',
            index=models.Index(fields=['entry_type', 'created_at'], name='owner_colle_entry_t_775442_idx'),
        ),
        migrations.AlterModelTable(
            name='ownerwithdrawal',
            table='owner_collections',
        ),
    ]
