# Generated by Django 5.2.14 on 2026-06-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_ownerwithdrawal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownerwithdrawal',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Sales Deposit', 'verbose_name_plural': 'Sales Deposits'},
        ),
        migrations.AlterField(
            model_name='ownerwithdrawal',
            name='entry_type',
            field=models.CharField(choices=[('visit', 'Visit'), ('leftover', 'Leftover')], default='visit', max_length=20),
        ),
    ]
