# Generated by Django 5.2.14 on 2026-05-24 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('summary', models.TextField(blank=True)),
                ('check_ins_count', models.PositiveIntegerField(default=0)),
                ('check_outs_count', models.PositiveIntegerField(default=0)),
                ('reservations_count', models.PositiveIntegerField(default=0)),
                ('cancellations_count', models.PositiveIntegerField(default=0)),
                ('maintenance_rooms_count', models.PositiveIntegerField(default=0)),
                ('cleaning_rooms_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_handovers_prepared', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ended_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftHandoverUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_handover_updates', to=settings.AUTH_USER_MODEL)),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='shifts.shifthandover')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
