# Generated by Django 5.2.14 on 2026-06-02 09:52

from django.db import migrations, models


def seed_inventory_taxonomy(apps, schema_editor):
    InventoryCategory = apps.get_model("inventory", "InventoryCategory")
    InventorySubcategory = apps.get_model("inventory", "InventorySubcategory")
    Supplier = apps.get_model("inventory", "Supplier")

    category_map = {}
    for name, group in [
        ("Non-alcoholic beverages", "non_alcoholic"),
        ("Alcoholic beverages", "alcoholic"),
        ("Foodstuff", "foodstuff"),
    ]:
        category, _ = InventoryCategory.objects.update_or_create(
            name=name,
            defaults={"category_group": group, "description": ""},
        )
        category_map[group] = category

    for category_group, subcategories in [
        (
            "non_alcoholic",
            ["Water", "Juices", "Soft Drinks", "Hot Beverages", "Dairy & Plant Milks"],
        ),
        (
            "alcoholic",
            ["Beers & Ciders", "Wines", "Spirits & Liquors", "Cocktails"],
        ),
        (
            "foodstuff",
            [
                "Staples (Grains, Tubers)",
                "Proteins (Meat, Fish)",
                "Fresh Produce (Fruits, Vegetables)",
                "Dairy",
                "Fats/Oils",
                "Pantry Essentials (Spices, Condiments)",
            ],
        ),
    ]:
        category = category_map[category_group]
        for subcategory_name in subcategories:
            InventorySubcategory.objects.update_or_create(
                category=category,
                name=subcategory_name,
                defaults={"description": ""},
            )

    for supplier_name in [
        "Kwadwo Boat Ventures",
        "Voltic Ghana",
        "Kasapreko Company",
        "Market",
    ]:
        Supplier.objects.update_or_create(
            name=supplier_name,
            defaults={"is_active": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_i_sku_e27286_idx',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='sku',
        ),
        migrations.AlterField(
            model_name='inventorycategory',
            name='category_group',
            field=models.CharField(choices=[('non_alcoholic', 'Non-alcoholic beverages'), ('alcoholic', 'Alcoholic beverages'), ('foodstuff', 'Foodstuff')], max_length=20),
        ),
        migrations.RunPython(seed_inventory_taxonomy, migrations.RunPython.noop),
    ]
