# Generated by Django 5.2.14 on 2026-06-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventoryitem_inventory_i_sku_e27286_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], default='active', max_length=20),
        ),
    ]
