# Generated by Django 5.2.14 on 2026-06-04 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_status'),
        ('rooms', '0004_maintenancerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='ToiletryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_in_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit_of_measure', models.CharField(choices=[('piece', 'Piece'), ('bottle', 'Bottle'), ('pack', 'Pack'), ('roll', 'Roll'), ('box', 'Box'), ('carton', 'Carton')], default='piece', max_length=20)),
                ('minimum_stock_threshold', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['quantity_in_stock'], name='inventory_t_quantit_1f5af7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ToiletryIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toiletry_issues', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toiletry_issues', to='rooms.room')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='inventory.toiletryitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='inventory_t_created_ad658a_idx')],
            },
        ),
    ]
