# Generated by Django 5.2.14 on 2026-06-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_inventoryitem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("low_stock", "Low Stock"),
                    ("out_of_stock", "Out of Stock"),
                    ("discontinued", "Discontinued"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
