# Generated by Django 5.2.14 on 2026-05-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='digital_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='guest',
            name='ghana_card_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='ghana_card_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='guest',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('miss', 'Miss'), ('sir', 'Sir')], max_length=10),
        ),
    ]
