# Generated by Django 5.2.14 on 2026-06-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guest_digital_address_guest_ghana_card_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blacklisted', 'Blacklisted'), ('no_show', 'No-show')], default='active', max_length=20),
        ),
    ]
